---
- name: Ensure Remi repository is installed.
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm

- name: Ensure repositories are disabled.
  replace:
    dest: /etc/yum.repos.d/{{ item }}
    regexp: "enabled *= *1"
    replace: "enabled=0"
  with_items:
    - remi.repo
    - remi-safe.repo
